services:
  # TODO: make the default here a volume based dev env like backend is
  spiffworkflow-frontend:
    container_name: spiffworkflow-frontend
    image: ghcr.io/sartography/spiffworkflow-frontend:latest
    environment:
      APPLICATION_ROOT: "/"
      PORT0: "${SPIFFWORKFLOW_FRONTEND_PORT}"
    ports:
      - "${SPIFFWORKFLOW_FRONTEND_PORT}:${SPIFFWORKFLOW_FRONTEND_PORT}/tcp"

  spiffworkflow-backend:
    container_name: spiffworkflow-backend
    build:
      context: ../../sartography/spiff-arena/spiffworkflow-backend
      dockerfile: $PWD/sartography/backend/Dockerfile
    environment:
      FLASK_APP: "/app/src/spiffworkflow_backend"
      FLASK_DEBUG: "1"
      FLASK_RUN_PORT: "${SPIFFWORKFLOW_BACKEND_PORT}"
      FLASK_SESSION_SECRET_KEY: "${FLASK_SESSION_SECRET_KEY}"
      SPIFFWORKFLOW_BACKEND_APPLICATION_ROOT: "/"
      SPIFFWORKFLOW_BACKEND_ENV: "local_development"
      # WARNING: Frontend is a static site which assumes frontend port - 1 on localhost.
      SPIFFWORKFLOW_BACKEND_URL: "http://localhost:${SPIFFWORKFLOW_BACKEND_PORT}"

      SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR: "/app/process_models"
      SPIFFWORKFLOW_BACKEND_CONNECTOR_PROXY_URL: "http://spiffworkflow-connector:8004"
      SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA: "false"
      SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_ID: "spiffworkflow-backend"
      SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_SECRET_KEY: "my_open_id_secret_key"
      SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL: "http://localhost:${SPIFFWORKFLOW_BACKEND_PORT}/openid"
      SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME: "example.yml"
      SPIFFWORKFLOW_BACKEND_PORT: "${SPIFFWORKFLOW_BACKEND_PORT}"
      SPIFFWORKFLOW_BACKEND_RUN_BACKGROUND_SCHEDULER: "true"
      SPIFFWORKFLOW_BACKEND_URL_FOR_FRONTEND: "http://localhost:${SPIFFWORKFLOW_FRONTEND_PORT}"
      SPIFFWORKFLOW_BACKEND_ENGINE_STEP_STRATEGY_BACKGROUND: "greedy"
      SPIFFWORKFLOW_BACKEND_ENGINE_STEP_STRATEGY_WEB: "run_until_service_task"
      SPIFFWORKFLOW_BACKEND_LOG_LEVEL: "info"
      SPIFFWORKFLOW_BACKEND_BACKGROUND_SCHEDULER_POLLING_INTERVAL_IN_SECONDS: "1"

      # Secrets - TODO update now that it is one conn str
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    ports:
      - "${SPIFFWORKFLOW_BACKEND_PORT}:${SPIFFWORKFLOW_BACKEND_PORT}/tcp"
    volumes:
      # TODO: should this be copied as the last step once the script settles
      - ./sartography/backend/bin:/app/bin
      - ../../sartography/sample-process-models:/app/process_models
      - ../../sartography/spiff-arena/spiffworkflow-backend/src:/app/src
      - ../../sartography/spiff-arena/spiffworkflow-backend/tests:/app/tests
