services:
  spiffworkflow-backend:
    environment:
      SPIFFWORKFLOW_BACKEND_DATABASE_TYPE: "sqlite"
      # TODO: i'd like to specify this but don't know how it works with tests yet
      #   see FLASK_INSTANCE_PATH
      #SPIFFWORKFLOW_BACKEND_DATABASE_URI: "sqlite:////app/db/db_local_development.sqlite3"
