[package]
name = "jbirddog/jbdcgi"
version = "0.1.3"
description = "Description for package jbdcgi"

[fs]
"/templates" = "templates"

[[module]]
name = "jbdcgi"
source = "hello.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "jbdcgi"
module = "jbdcgi"
runner = "wcgi"
[command.annotations.wcgi]
dialect = "rfc-3875"
